// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pbnclmmyxvjawpctlooc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBibmNsbW15eHZqYXdwY3Rsb29jIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkyMzg1NzQsImV4cCI6MjA2NDgxNDU3NH0.p5tE_FnNwjb44jFhw7rMVRf5XW6VF0uS0kWuDgFIoRU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});